import 'dart:ui';

enum MyTextType {
  displayLarge,
  displayMedium,
  displaySmall,
  headlineLarge,
  headlineMedium,
  headlineSmall,
  titleLarge,
  titleMedium,
  titleSmall,
  bodyLarge,
  bodyMedium,
  bodySmall,
  labelLarge,
  labelMedium,
  labelSmall,
}

Map<MyTextType, double> defaultTextSize = {
  MyTextType.displayLarge: 57,
  MyTextType.displayMedium: 45,
  MyTextType.displaySmall: 36,
  MyTextType.headlineLarge: 32,
  MyTextType.headlineMedium: 28,
  MyTextType.headlineSmall: 26,
  MyTextType.titleLarge: 22,
  MyTextType.titleMedium: 16,
  MyTextType.titleSmall: 14,
  MyTextType.labelLarge: 14,
  MyTextType.labelMedium: 12,
  MyTextType.labelSmall: 11,
  MyTextType.bodyLarge: 16,
  MyTextType.bodyMedium: 14,
  MyTextType.bodySmall: 12,
};
Map<MyTextType, double> defaultLetterSpacing = {
  MyTextType.displayLarge: -0.25,
  MyTextType.displayMedium: 0,
  MyTextType.displaySmall: 0,
  MyTextType.headlineLarge: -0.2,
  MyTextType.headlineMedium: -0.15,
  MyTextType.headlineSmall: 0,
  MyTextType.titleLarge: 0,
  MyTextType.titleMedium: 0.1,
  MyTextType.titleSmall: 0.1,
  MyTextType.labelLarge: 0.1,
  MyTextType.labelMedium: 0.5,
  MyTextType.labelSmall: 0.5,
  MyTextType.bodyLarge: 0.5,
  MyTextType.bodyMedium: 0.25,
  MyTextType.bodySmall: 0.4,
};
Map<MyTextType, FontWeight> defaultTextFontWeight = {
  MyTextType.displayLarge: FontWeight.w500,
  MyTextType.displayMedium: FontWeight.w500,
  MyTextType.displaySmall: FontWeight.w500,
  MyTextType.headlineLarge: FontWeight.w500,
  MyTextType.headlineMedium: FontWeight.w500,
  MyTextType.headlineSmall: FontWeight.w500,
  MyTextType.titleLarge: FontWeight.w500,
  MyTextType.titleMedium: FontWeight.w500,
  MyTextType.titleSmall: FontWeight.w500,
  MyTextType.labelLarge: FontWeight.w600,
  MyTextType.labelMedium: FontWeight.w600,
  MyTextType.labelSmall: FontWeight.w600,
  MyTextType.bodyLarge: FontWeight.w500,
  MyTextType.bodyMedium: FontWeight.w500,
  MyTextType.bodySmall: FontWeight.w500,
};
